### ISSUE TITLE
What if I want to test against an Ionic app?

### ISSUE THREAD

**Issue by fmsouza** [Nike-Inc/burnside#10]
Currently I'm diving into some alternatives for e2e testing to decide which to go with in a new project on my company. And the environment consists in an Ionic 3 application with native features, so it's a mostly a webapp but must be run in the mobile device.

Actually I have a setup working to test it this way using Protractor + Appium, and now I'm trying to do the same with Nightwatch as suggested by some people on my team.

As you are proposing this framework to be alternative to Nightwatch I may ask you: does it have the capability to be executed testing against an ionic app right on the device?

**Comment by BenAHammond** [comment]
Hi there, thanks for the inquiry.

Any device that can run Node and a Browser should be able to execute Burnside tests. Burnside works by running a small NodeJS server that it uses as a forward proxy to inject its Client into and then bundle your tests with its Core.  If your Ionic app is available over HTTP(S) you should be able to then test it.

Now, with that said, there are other configurations you could try if you need distributed testing. For instance you can pre-inject Burnside's Client into your app and then deploy the test bundle Burnside creates as static assets in the cloud. This technique can also be used to test with other browsers.

**Comment by BenAHammond** [comment]
Just to be clear though: Burnside tests web pages with javascript. Don't expect it to test native applications running outside of a browser.

**Comment by mrsanz** [comment]
Closing for now. @fmsouza Please confirm that this answered your question and if you have a chance play around with Burnside.  Cheers!

**Comment by fmsouza** [comment]
@mrsanz Yes, it did. My only point of concern now about mobile hybrid application is with the parts that make use of native resources, like a camera interaction. But I'll try it before making any assumptions. I'll take a look later, thanks!

**Comment by mrsanz** [comment]
@fmsouza I could see could utilizing Burnside to stub out those parts of the native functionality with functions that validate the ionic libraries contract.   For instance you could write a function that matches the interface of the native camera that ionic provides.  So then you could test the bulk of your interactions.  It wouldn't beat a native e2e test, but you'd be able to test your contract with the specific version of ionic.

**Comment by fmsouza** [comment]
Seems like a great starting point! I'll certainly try it on my setup and come back in case I miss something. Thank you for the help!
