### ISSUE TITLE
File not found error on "npm run custom-install"

### ISSUE THREAD

**Issue by joeJazdzewski** [Nike-Inc/burnside#11]
When I followed the following steps
```
git clone https://github.com/Nike-Inc/burnside.git

cd burnside
npm install && npm run custom-install
npm run tutorial
```

I got the following error on "npm run custom-install"
 `ENOENT: no such file or directory, stat '\burnside\packages\burnside-localproxy\lib\cli.js`

Thanks in advanced.

**Comment by BenAHammond** [comment]
Looks like you're missing the built libraries. Can you try running `npm run
prepublish` inside `\burnside\packages\burnside-localproxy\`

**Comment by BenAHammond** [comment]
I was able to reproduce your issue but only on windows. I wonder if lerna is the problem.

**Comment by BenAHammond** [comment]
Looks like it was the cleanup scripts.

https://github.com/Nike-Inc/burnside/pull/12

**Comment by joeJazdzewski** [comment]
Sorry I forgot to mention that I am using windows 10, node 6.11.4, and npm 3.10.10

**Comment by BenAHammond** [comment]
Can you pull the latest changes from master and try again?

**Comment by joeJazdzewski** [comment]
I pulled from master and I am still getting the same error.

**Comment by BenAHammond** [comment]
Hm, maybe try deleting and cloning again then.

**Comment by jbardrof** [comment]
I can confirm I'm receiving the same error, just pulled latest.

**Comment by BenAHammond** [comment]
Okay, thanks! I will investigate further, its possible I still have local changes on my windows machine.

**Comment by BenAHammond** [comment]
Good news! I was able to reproduce the issue once more and found an easier solution. Rather than building all of the packages and cross installing their dependencies with Lerna its much simpler to just fetch the CLI's deps straight for NPM for Windows users.

I'll update the docs if this works for you as well.

```
git clone https://github.com/Nike-Inc/burnside.git

cd burnside\packages\burnside-cli && npm install && npm run tutorial```

**Comment by jbardrof** [comment]
That works, thank you!

**Comment by joeJazdzewski** [comment]
works for me too

**Comment by BenAHammond** [comment]
Great!

Here's a PR for the changes https://github.com/Nike-Inc/burnside/pull/14
