### ISSUE TITLE
Buggy scroll restoration on nike.com website

### ISSUE THREAD

**Issue by l-you** [Nike-Inc/burnside#16]
Could you please guide me on how to get in touch with Nike’s website developers regarding a usability bug on nike.com? I have a clear video reproduction of bug related to scroll restoration. That issue is really annoying for me as a customer.

**Comment by BenAHammond** [comment]
I no longer work at Nike but I can try to give someone the details if you want to leave them here.

**Comment by l-you** [comment]
@BenAHammond  I would appreciate this. Thank you!

I discovered an issue while browsing the nike.com product catalog. The catalog contains a large infinite list of items. When I click on a product to view more details the IOS navigation bar disappears. To make it reappear, I have to scroll to the top and immediately click the 'back' navigation button. However, the scroll position resets to the top once the navigation transition is finished, forcing me to manually scroll back to the bottom again. It's hard to find the position where I was before. On other websites, the scroll position is retained when I navigate back. 
This bug occurs **only** on IOS Safari; however, the Google Chrome browser on the same OS works as expected.
Please watch the following video to see the issue being reproduced.


https://github.com/Nike-Inc/burnside/assets/32598874/bb7665dd-b866-495f-94a1-6691686d0677

**Comment by l-you** [comment]
The solution is to not use the Nike website. They should probably be more open to customer feedback.
